spring.application.name=challenge-api

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/challengeDB
spring.datasource.username=challenge_user
spring.datasource.password=challenge_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenAPI Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html